# Generated by Django 5.0.6 on 2024-06-30 14:32

import ckeditor.fields
import york_site.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image_1', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Зображення банер 1')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 1')),
                ('desc_1', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 1')),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 1')),
                ('tab_url_1', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 1')),
                ('image_2', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Зображення банер 2')),
                ('h_2', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 2')),
                ('desc_2', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 2')),
                ('tab_2', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 2')),
                ('tab_url_2', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 2')),
                ('image_3', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Зображення банер 3')),
                ('h_3', models.CharField(blank=True, max_length=250, verbose_name='Заголовок банер 3')),
                ('desc_3', models.TextField(blank=True, max_length=500, verbose_name='Опис банер 3')),
                ('tab_3', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки банер 3')),
                ('tab_url_3', models.URLField(blank=True, verbose_name='Посилання з кнопки банер 3')),
            ],
            options={
                'verbose_name_plural': 'Банер',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(max_length=70, verbose_name='Адреса')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('phone_3', models.CharField(blank=True, max_length=50, verbose_name='Телефон 3')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта ')),
                ('day_open', models.CharField(blank=True, max_length=50, verbose_name='Робочі дні')),
                ('weekend_work', models.CharField(blank=True, max_length=50, verbose_name='Робота в вихідні')),
                ('weekend_hours_of_work', models.CharField(blank=True, max_length=50, verbose_name='Робочі години в вихідні')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/', verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "Зворотній зв'язок",
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(verbose_name='Позиція')),
                ('image', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Зображення')),
                ('image_bg', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Фонове зображення')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('h_1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('tab', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('tab_url', models.URLField(blank=True, verbose_name='Посилання з кнопки')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
    ]
