# Generated by Django 5.0.6 on 2024-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='fb_url',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='in_url',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='contacts',
            name='hours_of_work',
            field=models.CharField(blank=True, max_length=50, verbose_name='Робочі години'),
        ),
    ]
