# Generated by Django 5.0.6 on 2024-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_contacts_fb_url_remove_contacts_in_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='map_url_address',
            field=models.URLField(blank=True, verbose_name='Посилання на google map'),
        ),
    ]
