# Generated by Django 5.0.6 on 2024-07-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baner',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='baner',
            name='h_3',
        ),
        migrations.RemoveField(
            model_name='baner',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='baner',
            name='tab_3',
        ),
        migrations.RemoveField(
            model_name='baner',
            name='tab_url_3',
        ),
    ]
