# Generated by Django 4.2.4 on 2024-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_baner_desc_3_remove_baner_h_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='price',
        ),
        migrations.AddField(
            model_name='hero',
            name='main_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
