# Generated by Django 4.2.4 on 2024-11-14 22:22

import ckeditor.fields
from django.db import migrations, models
import york_site.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_rename_main_price_hero_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Image')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Image')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to=york_site.utils.get_file_name_id, verbose_name='Image'),
        ),
    ]
