# Generated by Django 5.0.6 on 2024-08-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Out of Stock'), ('I', 'In stock'), ('S', 'Soon in stock')], default='N', max_length=1),
        ),
    ]
