# Generated by Django 4.2.4 on 2024-11-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
    ]
