# Generated by Django 4.2.4 on 2024-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_sale'),
        ('store', '0009_remove_product_is_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='category.category'),
        ),
    ]
