# Generated by Django 5.0.6 on 2024-06-23 21:10

import york_site.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=york_site.utils.get_file_name, verbose_name='Image')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('description', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('category_main_page', models.BooleanField(default=False, verbose_name='Visible on main page')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta-teg Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta-teg Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Сategories',
            },
        ),
    ]
