# Generated by Django 4.2.4 on 2024-11-24 19:42

from django.db import migrations, models
import york_site.utils


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=york_site.utils.get_file_name, verbose_name='Image')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('description', models.CharField(max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta-teg Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta-teg Description')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
