# Generated by Django 4.2.4 on 2024-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category_main_page',
            field=models.BooleanField(default=False, verbose_name='Visible on main page'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
