# Generated by Django 4.2.4 on 2024-11-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_is_sale'),
        ('category', '0003_sale_category_main_page_sale_is_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
