# Generated by Django 4.2.4 on 2024-12-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'Category', 'verbose_name_plural': 'Сategories'},
        ),
    ]
